/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable @next/next/no-html-link-for-pages */
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="z-10 fixed top-0 w-full">
        <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row pt-7 pb-9 border-b-2 border-black seashell">
          <div className="flex flex-row items-center justify-between p-3 md:p-1">
            <a href="/" className="cursor-pointer font-semibold">
              <h1 className="text-4xl">RetroArt</h1>
            </a>
            <button
              className="text-white pb-4 cursor-pointer leading-none px-3 py-1 md:hidden outline-none focus:outline-none content-end ml-auto"
              type="button"
              aria-label="button"
            ></button>
          </div>
          <div className="lg:flex flex-grow items-center hidden">
            <div className="text-black md:ml-auto md:mr-auto pt-3 md:pl-14 pl-1 flex flex-wrap items-center md:text-lg text-2xl md:justify-center justify-items-start">
              <a href="/" className="mr-5 pr-2 cursor-pointer font-semibold">
                Discover
              </a>
              <a
                href="/"
                className="mr-14 md:ml-11 ml-0 cursor-pointer font-semibold"
              >
                Artwork
              </a>
              <a href="/" className="mr-5 cursor-pointer font-semibold">
                How it works
              </a>
            </div>
            <a
              className="inline-flex items-center px-9 py-5 mt-2 font-semibold text-md bg-black text-white"
              href="/"
            >
              Collect a Wallet
            </a>
          </div>
        </div>
      </header>
      <main>
        <div className="container mx-auto flex pt-64 md:flex-row flex-col items-center">
          <div className="lg:flex-grow xl:w-1/2 pt-6 flex flex-col md:items-start md:text-left mb-40 items-center text-center">
            <h1 className="mb-5 font-semibold sm:text-8xl text-5xl items-center xl:w-2/2 text-black">
              Collect RetroArt
              <br />
              Digital Artwork
            </h1>
            <p className="text-xl font-semibold my-5 xl:w-3/4 text-black">
              Buy and sell NFTs from the world's top sites
            </p>
            <div className="flex justify-center">
              <a
                className="z-0 inline-flex items-center px-12 py-5 mt-2 font-medium text-white transform bg-transparent bg-black"
                href="/"
              >
                <span className="justify-center">Get Started</span>
              </a>
            </div>
          </div>
          <div className="ylw mr-0 lg:mr-44">
            <img
              className=""
              src="https://i.gyazo.com/8ceb54a9f3198a9c60ed8479a4adb5b2.png"
              alt=""
              width="480"
              height="500"
            />
            <div className="pt-6 space-y-4">
              <div className="pl-8 mb-4">
                <h2 className="text-4xl font-semibold">TERRAFORM</h2>
              </div>
              <div className="pl-8">
                <h3 className="text-sm text-gray-500">Reserve Price</h3>
                <h3 className="text-2xl font-semibold inline-block">
                  2.00 ETH{" "}
                  <h4 className="text-sm text-gray-800 inline-block">
                    ($4,891.22)
                  </h4>
                </h3>
              </div>
              <div className="pb-8">
                <a
                  className="inline-flex items-center px-11 py-4 ml-8 mt-2 font-semibold text-md border-2 border-black bg-black text-white"
                  href="/"
                >
                  Place a Bid
                </a>
                <a
                  className="inline-flex items-center px-9 py-4 sm:ml-3 mt-2 md:ml-8 lg:ml-6 font-semibold text-md border-2 border-black text-black"
                  href="/"
                >
                  View Artwork
                </a>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
